

voxel_autoencoderkl:
  in_channels: 1
  out_channels: 1
  latent_dim: 16
  base_channels: 128
  multiplier: 2
  num_layers: 3

image_feature_extractor:
  model_id: stabilityai/sdxl-vae

image_feature_head:
  model_id: unet_encoder2d
  in_channels: 4
  latent_dim: 2048
  base_channels: 64
  multiplier: 2
  num_layers: 3

decoder:
  hidden_size: 2048
  num_attention_layers: 12
  num_heads: 16
  head_size: 128

scheduler:
  prediction_type: epsilon